export {default as Home } from './home/Home'
export {default as About  } from './about/About'
export {default as Project } from './project/Project'
export {default as Skill } from './skill/Skill'
export {default as Modal } from './modal/Modal'